#!/bin/sh
docker run -v $(pwd):/app alpine sh -c "apk update && apk add py-pip python && cd app && pip install -r requirements.txt && pip install -r test-requirements.txt && pip install . && python setup.py test"
